"""Add lat and lng columns to map_location table

Revision ID: d01258bcd434
Revises: ec83b1237404
Create Date: 2025-03-05 22:10:44.169975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.types import NullType


# revision identifiers, used by Alembic.
revision = 'd01258bcd434'
down_revision = 'ec83b1237404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))
        # Skip altering the geometry column as it's already set up correctly
        # batch_op.alter_column('geometry',
        #        existing_type=NullType(),
        #        nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_location', schema=None) as batch_op:
        # Skip altering the geometry column
        # batch_op.alter_column('geometry',
        #        existing_type=NullType(),
        #        nullable=True)
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
