"""Initial migration.

Revision ID: f2a8fcde7cd4
Revises: 
Create Date: 2025-03-04 22:22:30.266255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a8fcde7cd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geometry', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('MapLocation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MapLocation',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.NVARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.NVARCHAR(), autoincrement=False, nullable=True),
    sa.Column('geometry', sa.NVARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.NVARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__MapLocat__3213E83FF72E497E')
    )
    op.drop_table('map_location')
    # ### end Alembic commands ###
